[tool.black]
line-length = 120
target-version = ['py39']
exclude = '''
/(
    \.git
  | \.hg
  | \.pytest_cache
  | \.tox
  | \.venv
  | _build
  | build_scripts
  | buck-out
  | build
  | dist
)/
'''
[tool.isort]
profile = "black"
py_version = 39
line_length = 120
skip = ["build_scripts/",".pytest_cache/",".venv/",".git/", ".tox/"]
multi_line_output = 3
combine_as_imports = true
force_grid_wrap = 0
